name: build
jobs:
  build:
    runs-on: steden88/cicd:2.0 # 工作流运行的环境
    steps:
      - name: 开启Git代理
        uses: gitProxy@v1
        with:
          proxy: "socks5://192.168.1.88:7890"

      - name: 安装GO
        uses: setup-go@v1
        with:
          goVersion: go1.22.0
          goDownload:

      - name: 拉取应用Git
        uses: checkout@v1

      - name: 编译
        run:
          - rm -rf ./go.work
          - go work init ./
          - go work edit -replace github.com/farseer-go/fs=../farseer-go/fs
          - go work edit -replace github.com/farseer-go/utils=../farseer-go/utils
          - go work edit -replace github.com/farseer-go/mapper=../farseer-go/mapper
          - go mod download
          - go mod tidy
          - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o ./app-server -ldflags="-w -s" .

      - name: 打包镜像
        uses: dockerBuild@v1

      - name: 上传镜像
        uses: dockerPush@v1

      - name: 更新镜像
        uses: dockerswarmUpdateVer@v1