name: build
jobs:
  clusterId: [3]
  build:
    runs-on: steden88/cicd:3.0 # 工作流运行的环境
    proxy: "http://192.168.1.8:7890"
    env:
      GO111MODULE: on
      GOPROXY: https://goproxy.cn,direct

    steps:
      - name: 安装GO
        uses: setup-go@v1
        with:
          goVersion: go1.22.5
          goDownload:

      - name: 拉取应用Git
        uses: checkout@v1

      - name: 编译
        run:
          - unset HTTPS_PROXY
          - unset HTTP_PROXY
          - rm -rf ./go.work
          - go work init ./
          - go work edit -replace github.com/farseer-go/fs=../farseer-go/fs
          - go work edit -replace github.com/farseer-go/data=../farseer-go/data
          - go work edit -replace github.com/farseer-go/data/driver/clickhouse=../farseer-go/data/driver/clickhouse
          - go work edit -replace github.com/farseer-go/mapper=../farseer-go/mapper
          - go work edit -replace github.com/farseer-go/queue=../farseer-go/queue
          - go work edit -replace github.com/farseer-go/utils=../farseer-go/utils
          - go work edit -replace github.com/farseer-go/eventBus=../farseer-go/eventBus
          - go work edit -replace github.com/farseer-go/collections=../farseer-go/collections
          - go work edit -replace github.com/farseer-go/redis=../farseer-go/redis
          - go work edit -replace github.com/farseer-go/cache=../farseer-go/cache
          - go work edit -replace github.com/farseer-go/cacheMemory=../farseer-go/cacheMemory
          - go work edit -replace github.com/farseer-go/elasticSearch=../farseer-go/elasticSearch
          - go work edit -replace github.com/farseer-go/webapi=../farseer-go/webapi
          - go work edit -replace github.com/farseer-go/tasks=../farseer-go/tasks
          - go work edit -replace github.com/farseer-go/fSchedule=../farseer-go/fSchedule
          - go work edit -replace github.com/farseer-go/rabbit=../farseer-go/rabbit
          - go work edit -replace github.com/farseer-go/linkTrace=../farseer-go/linkTrace
          - go mod download
          - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o ./FSchedule -ldflags="-w -s" .

      - name: 打包镜像
        uses: dockerBuild@v1

      - name: 上传镜像
        uses: dockerPush@v1

      - name: 更新镜像
        uses: dockerswarmUpdateVer@v1
        with:
          remoteClusterId: 1